//! Frozen accepted-CLI wire bytes; never generated by candidate serializers.
use super::*;

const ACCEPTED_OLD_V3: &[u8] = include_bytes!("../../tests/fixtures/accepted-old-v3.json");

fn bytes(capsule: &serde_json::Value, path: &str) -> Vec<u8> {
    let encoded = capsule["entries"][path].as_str().unwrap();
    assert_eq!(encoded.len() % 2, 0);
    (0..encoded.len())
        .step_by(2)
        .map(|index| u8::from_str_radix(&encoded[index..index + 2], 16).unwrap())
        .collect()
}

#[test]
fn accepted_old_v3_retained_deltas_roundtrip_exact_bytes_and_proof_hashes() {
    let capsule: serde_json::Value = serde_json::from_slice(ACCEPTED_OLD_V3).unwrap();
    assert_eq!(
        capsule["provenance"]["binary_sha256"],
        "ec1478bdd0a14f3bfc1a9d89c0eeb2c8b0f130515d2068153d81cd8739ede146"
    );
    let receipts = capsule["receipts"].as_array().unwrap();
    assert_eq!(receipts.len(), 3);
    for item in receipts {
        let original = bytes(&capsule, item["delta_path"].as_str().unwrap());
        let decoded: RetainedDelta = strict_json(&original).unwrap();
        assert_eq!(decoded.version, 3);
        assert_eq!(serde_json::to_vec(&decoded).unwrap(), original);
        let receipt: serde_json::Value =
            serde_json::from_slice(&bytes(&capsule, item["validation_path"].as_str().unwrap()))
                .unwrap();
        let proof: IndexedRefreshProof = serde_json::from_value(receipt["proof"].clone()).unwrap();
        assert_eq!(Blake3Hash::digest(&original), proof.delta_hash);
        assert_eq!(decoded.change, proof.change);
        assert_eq!(decoded.base, proof.base);
        assert_eq!(decoded.before, proof.before);
        assert_eq!(decoded.after, proof.after);
        assert_eq!(decoded.operation, proof.operation);
        assert_eq!(decoded.source_id, proof.source_id);
    }
}

#[test]
fn specified_deployed_v2_full_delta_roundtrip_exact_bytes_and_bound_hash() {
    let capsule: serde_json::Value = serde_json::from_slice(include_bytes!(
        "../../tests/fixtures/specified-old-v2-pending.json"
    ))
    .unwrap();
    assert_eq!(
        capsule["provenance"]["spec_commit"],
        "60603e231299c206f334bd42b2f742b3ad40511f"
    );
    assert_eq!(capsule["provenance"]["emitted_by_v2_cli"], false);
    let validation_path = capsule["validation_path"].as_str().unwrap();
    let receipt: serde_json::Value =
        serde_json::from_slice(&bytes(&capsule, validation_path)).unwrap();
    let proof: IndexedRefreshProof = serde_json::from_value(receipt["proof"].clone()).unwrap();
    let original = bytes(
        &capsule,
        &validation_path.replace("validation.json", "indexed-delta.json"),
    );
    let decoded: RetainedDelta = strict_json(&original).unwrap();
    assert_eq!(decoded.version, 2);
    assert_eq!(decoded.rows.version, 2);
    assert!(decoded.operation.is_none());
    assert!(decoded.rows.facts.as_ref().unwrap().policy.is_none());
    assert_eq!(serde_json::to_vec(&decoded).unwrap(), original);
    assert_eq!(Blake3Hash::digest(&original), proof.delta_hash);
    assert_eq!(decoded.source_id, proof.source_id);
    assert_eq!(decoded.change, proof.change);
    assert_eq!(decoded.base, proof.base);
    assert_eq!(decoded.before, proof.before);
    assert_eq!(decoded.after, proof.after);
    decoded.rows.validate().unwrap();
    assert_eq!(
        intended(&proof.base, &proof.change, &proof.delta_hash, 2).unwrap(),
        proof.intended
    );
}
